# Generated by Django 5.2.13 on 2026-04-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_context_movie_content_alter_movie_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='director_img_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director_works',
            field=models.TextField(blank=True, null=True),
        ),
    ]
