# Generated by Django 5.2.13 on 2026-04-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_director_img_url_movie_director_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director_img_url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_info',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_works',
        ),
    ]
