# Generated by Django 5.2.13 on 2026-04-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_name', models.CharField(max_length=120)),
                ('matched_company_name', models.CharField(blank=True, max_length=120)),
                ('stock_code', models.CharField(blank=True, max_length=80)),
                ('original_comments', models.JSONField(default=list)),
                ('cleaned_comments', models.JSONField(default=list)),
                ('augmented_comments', models.JSONField(default=list)),
                ('iqr_lower', models.FloatField(blank=True, null=True)),
                ('iqr_upper', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
